name: new_turki
description: A new project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.3
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_analytics: ^8.2.0
  firebase_in_app_messaging: ^0.5.0+7
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: ^0.4.0
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  flutter_svg: ^0.22.0
  auto_size_text: ^3.0.0-nullsafety.0
  webview_flutter: ^2.0.12
  flutter_advanced_drawer: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/placeholder.png
    - assets/images/amazon.png
    - assets/images/cash-back.png
    - assets/images/money.png
    - assets/images/favourites.png
    - assets/images/medal.png
    - assets/images/turki_icon.png
    - assets/images/turki.png
    - assets/images/w.png
    - assets/images/turki2.png
    - assets/images/Sheep.png
    - assets/images/naimi.png
    - assets/images/hary.png
    - assets/images/scooter.png
    - assets/images/pngpng-01.png
    - assets/images/pngpng-02.png
    - assets/images/pngpng-03.png
    - assets/images/pngpng-04.png
    - assets/images/weight.png
    - assets/images/star.png
    - assets/images/fire.png
    - assets/images/pngpng-05.png
    - assets/images/pngpng-06.png
    - assets/images/i1.png
    - assets/images/i2.png
    - assets/images/i3.png
    - assets/images/i4.png
    - assets/images/i5.png
    - assets/images/q1.png
    - assets/images/q2.png
    - assets/images/q3.jpg
    - assets/images/q4.bmp
    - assets/images/q5.png
    - assets/images/q6.png
    - assets/images/applepay.png
    - assets/images/cod.png
    - assets/images/mada.png
    - assets/images/mada2.png
    - assets/images/mada3.png
    - assets/images/master6.jpeg
    - assets/images/visa.png
    - assets/images/master.png
    - assets/language/ar.json
    - assets/language/en.json


  fonts:
    - family: Turki
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/light.otf
          weight: 300
    - family: RA7ICONS
      fonts:
        - asset: assets/icons/RA7ICONS.ttf
    - family: RA1ICONS
      fonts:
        - asset: assets/icons/RA1ICONS.ttf
    - family: SOCIALICONS
      fonts:
        - asset: assets/icons/SocialIcons.ttf