name: turki_dabayh
description:  turki app project.

version: 5.13.0+30

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  in_app_review: ^2.0.6
  http: ^0.13.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_analytics: ^10.1.0
  firebase_in_app_messaging: ^0.7.0+10
  firebase_dynamic_links: ^5.0.11
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.16
  provider: ^6.0.5
  auto_size_text: ^3.0.0
  webview_flutter: ^3.0.4
  flutter_advanced_drawer: ^1.3.2
  avatar_glow: ^2.0.2
  country_code_picker: ^2.0.2
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  url_launcher: ^6.1.7
  share_plus: ^6.3.0
  flutter_spinkit: ^5.1.0
  pin_code_fields: ^7.4.0
  flutter_picker: ^2.0.5
  readmore: ^2.2.0
  intl: ^0.17.0
  version: ^2.0.0
  tamara_sdk: ^0.9.1
  huawei_hmsavailability: ^6.6.0+300
  huawei_map: ^6.5.0+301
  huawei_location: ^6.4.0+300
  flutter_svg: ^1.1.6
  app_settings: ^4.2.0
  tabby_flutter_inapp_sdk: ^1.1.2
  get_it: ^7.2.0
  connectivity_plus: ^3.0.2
  lottie: ^2.2.0
  shake: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  flutter_lints: ^2.0.1



flutter_native_splash:
  #color: "#691E18"
  background_image: "assets/images/ww1.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/splash2.gif
    - assets/images/splash.gif
    - assets/images/whatsapp.png
    - assets/images/ww1.png
    - assets/images/wishlist.png
    - assets/images/almaraa_logo.png
    - assets/images/banner.png
    - assets/images/placeholder.png
    - assets/images/pin.png
    - assets/images/warning.png
    - assets/images/q1.png
    - assets/images/q2.png
    - assets/images/no_internet.gif
    - assets/images/tabby.png
    - assets/images/tamara_ar.png
    - assets/images/tamara_en.png
    - assets/images/turki_gold.png
    - assets/images/not_auth.png
    - assets/images/q5.png
    - assets/images/turki_icon_small.png
    - assets/images/turki.png
    - assets/images/q6.png
    - assets/images/turki_car.png
    - assets/images/medal.png
    - assets/images/no_orders.png
    - assets/images/location_p.png
    - assets/images/w.png
    - assets/images/turki_icon.png
    - assets/images/money.png
    - assets/images/t1.gif
    - assets/images/not_supported.png
    - assets/images/success.gif
    - assets/images/empty_cart.png
    - assets/images/about.png
    - assets/images/profile_icons/delete-account.svg
    - assets/images/profile_icons/rate.svg
    - assets/images/profile_icons/wrapping.svg
    - assets/images/profile_icons/questions-Maraa.svg
    - assets/images/profile_icons/quality.svg
    - assets/images/profile_icons/zabh.svg
    - assets/images/profile_icons/cut.svg
    - assets/images/profile_icons/delivery.svg
    - assets/images/profile_icons/medical-check.svg
    - assets/images/profile_icons/vision.svg
    - assets/images/profile_icons/goal.svg
    - assets/images/profile_icons/value.svg
    - assets/images/profile_icons/Classic-Mode.svg
    - assets/images/profile_icons/dark-mode.svg
    - assets/images/profile_icons/light.svg
    - assets/images/profile_icons/questions.svg
    - assets/images/profile_icons/logout.svg
    - assets/images/profile_icons/about.svg
    - assets/images/profile_icons/share-colored.svg
    - assets/images/profile_icons/whatsapp-colored.svg
    - assets/images/profile_icons/customer-support.svg
    - assets/images/profile_icons/favorites.svg
    - assets/images/profile_icons/my-addresses.svg
    - assets/images/profile_icons/user.svg
    - assets/images/profile_icons/orders.svg
    - assets/images/profile_icons/points.svg
    - assets/images/profile_icons/wallet.svg
    - assets/images/profile_icons/wallet6.svg
    - assets/images/profile_icons/wallet7.svg
    - assets/images/profile_icons/wallet8.svg
    - assets/images/profile_icons/logout-colored.svg
    - assets/images/profile_icons/language-color.svg
    - assets/images/profile_icons/home-location.svg
    - assets/language/ar.json
    - assets/language/en.json
    - assets/lottie/logo.json

  fonts:
    - family: Turki
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/light.otf
          weight: 300
    - family: TURKIICONS
      fonts:
        - asset: assets/icons/TURKIICONS.ttf
    - family: SOCIALICONS
      fonts:
        - asset: assets/icons/SocialIcons.ttf