name: turki_maraa_app
description: "Turki Dabayh app created by Rami Alamir"

publish_to: 'none'

version: 6.14.0+43

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  in_app_review: ^2.0.10
  http: ^1.4.0
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_analytics: ^11.5.2
  firebase_in_app_messaging: ^0.8.1+9
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  auto_size_text: ^3.0.0
  webview_flutter: ^4.13.0
  flutter_advanced_drawer: ^1.5.0
  avatar_glow: ^3.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  location: ^8.0.1
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  flutter_spinkit: ^5.2.1
  pin_code_fields: ^8.0.1
#  flutter_picker: ^2.1.0
  readmore: ^3.0.0
  intl: ^0.20.2
  version: ^2.0.0
  tamara_flutter_sdk: ^1.0.17
#  huawei_hmsavailability: ^6.12.0+300
#  huawei_map: ^6.11.2+303
#  huawei_location: ^6.12.0+303
  flutter_svg: ^2.2.0
  app_settings: ^6.1.1
  tabby_flutter_inapp_sdk: ^1.10.1
  get_it: ^8.0.3
  connectivity_plus: ^4.0.0
  lottie: ^3.3.1
#  shake: ^2.2.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  rate_my_app: ^2.3.2
  localstorage: ^4.0.0
  video_player: ^2.10.0
  flutter_local_notifications: ^19.3.1

#flutter_native_splash:
#  background_image: "assets/images/ww1.png"

dev_dependencies:
#  flutter_native_splash: ^2.4.2

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/turkieshop-c8917-firebase-adminsdk-0v51v-fd39c1d9be.json
    - assets/images/
    - assets/images/profile_icons/
    - assets/language/
    - assets/lottie/
    - assets/images/ww1.png
    - assets/videos/

  fonts:
    - family: Turki
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/light.otf
          weight: 300
    - family: Turki
      fonts:
        - asset: assets/fonts/harir/harir.otf
        - asset: assets/fonts/harir/harir_bold.otf
          weight: 700
    - family: TURKIICONS
      fonts:
        - asset: assets/icons/TURKIICONS.ttf
    - family: SOCIALICONS
      fonts:
        - asset: assets/icons/SocialIcons.ttf