name: turki_maraa_app
description: "Turki Dabayh app created by Rami Alamir"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 6.3.0+43

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  in_app_review: ^2.0.8
  http: ^0.13.6
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.16
  firebase_analytics: ^10.8.6
  firebase_in_app_messaging: ^0.7.4+14
  firebase_dynamic_links: ^5.4.14
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  auto_size_text: ^3.0.0
  webview_flutter: ^3.0.4
  flutter_advanced_drawer: ^1.3.5
  avatar_glow: ^3.0.1
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  flutter_spinkit: ^5.2.0
  pin_code_fields: ^8.0.1
#  flutter_picker: ^2.1.0
  readmore: ^2.2.0
  intl: ^0.19.0
  version: ^2.0.0
  tamara_sdk: ^0.9.1
  huawei_hmsavailability: ^6.12.0+300
  huawei_map: ^6.11.2+301
  huawei_location: ^6.12.0+301
  flutter_svg: ^2.0.9
  app_settings: ^5.1.1
  tabby_flutter_inapp_sdk: ^1.4.2
  get_it: ^7.6.7
  connectivity_plus: ^5.0.2
  lottie: ^3.0.0
  shake: ^2.2.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  rate_my_app: ^2.0.0
  localstorage: ^4.0.1+4
#flutter_native_splash:
#  background_image: "assets/images/ww1.png"
dev_dependencies:
#  flutter_native_splash:

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1



flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/profile_icons/
    - assets/language/
    - assets/lottie/
    - assets/images/ww1.png

  fonts:
    - family: Turki
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/light.otf
          weight: 300
    - family: Turki
      fonts:
        - asset: assets/fonts/harir/harir.otf
        - asset: assets/fonts/harir/harir_bold.otf
          weight: 700
    - family: TURKIICONS
      fonts:
        - asset: assets/icons/TURKIICONS.ttf
    - family: SOCIALICONS
      fonts:
        - asset: assets/icons/SocialIcons.ttf