name: turki_maraa_app
description: "Turki Dabayh app created by Rami Alamir"

publish_to: 'none'

version: 6.28.0+43

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  in_app_review: ^2.0.11
  http: ^1.5.0
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_analytics: ^12.0.1
  firebase_in_app_messaging: ^0.9.0+1
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  auto_size_text: ^3.0.0
  webview_flutter: ^4.13.0
  flutter_advanced_drawer: ^1.5.0
  avatar_glow: ^3.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  location: ^8.0.1
  url_launcher: ^6.3.2
  share_plus: ^12.0.0
  flutter_spinkit: ^5.2.2
  pin_code_fields: ^8.0.1
#  flutter_picker: ^2.1.0
  readmore: ^3.0.0
  intl: ^0.20.2
  version: ^2.0.0
  tamara_flutter_sdk: ^1.0.17
#  huawei_hmsavailability: ^6.12.0+300
#  huawei_map: ^6.11.2+303
#  huawei_location: ^6.12.0+303
  flutter_svg: ^2.2.1
  app_settings: ^6.1.1
  tabby_flutter_inapp_sdk: ^1.11.0
  get_it: ^8.2.0
  connectivity_plus: ^7.0.0
  lottie: ^3.3.2
#  shake: ^2.2.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  rate_my_app: ^2.3.2
  localstorage: ^6.0.0
  video_player: ^2.10.0
  flutter_local_notifications: ^19.4.1
  flutter_inappwebview: ^6.1.5
  flutter_smartlook: ^4.1.29
  adjust_sdk: ^5.4.2

#flutter_native_splash:
#  background_image: "assets/images/ww1.png"

dev_dependencies:
#  flutter_native_splash: ^2.4.2

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/turkieshop-c8917-firebase-adminsdk-0v51v-fd39c1d9be.json
    - assets/images/
    - assets/images/profile_icons/
    - assets/language/
    - assets/lottie/
    - assets/images/ww1.png
    - assets/videos/

  fonts:
    - family: Turki
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/light.otf
          weight: 300
    - family: Turki
      fonts:
        - asset: assets/fonts/harir/harir.otf
        - asset: assets/fonts/harir/harir_bold.otf
          weight: 700
    - family: TURKIICONS
      fonts:
        - asset: assets/icons/TURKIICONS.ttf
