name: new_turki
description: A new project.

version: 5.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.4
  firebase_core: ^1.11.0
  firebase_messaging: ^11.1.0
  firebase_analytics: ^8.3.4
  firebase_in_app_messaging: ^0.5.0+13
  firebase_dynamic_links: ^4.0.4
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: 0.4.1
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  flutter_svg: ^0.23.0+1
  auto_size_text: ^3.0.0
  webview_flutter: ^3.0.0
  flutter_advanced_drawer: ^1.3.0
  avatar_glow: ^2.0.2
  country_code_picker: ^2.0.2
  geocoding: ^2.0.2
  #geolocator: ^8.1.0
  google_maps_flutter: ^2.1.1
  location: ^4.3.0
  url_launcher: ^6.0.18
  share: ^2.0.4
  flutter_spinkit: ^5.1.0
  pin_code_fields: ^7.3.0
  flutter_dropdown_alert: ^1.0.3
  flutter_picker: ^2.0.2
  readmore: ^2.1.0
  #permission_handler: ^8.3.0
  app_settings: ^4.1.1
  intl: ^0.17.0
  tamara_sdk: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_native_splash: ^1.3.2



flutter_native_splash:
  #color: "#691E18"
  background_image: "assets/images/ww1.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/splash.gif
    - assets/images/wishlist.png
    - assets/images/pin.png
    - assets/images/i.png
    - assets/images/q1.png
    - assets/images/q2.png
    - assets/images/no_internet.gif
    - assets/images/turki_gold.png
    - assets/images/not_auth.png
    - assets/images/q5.png
    - assets/images/q6.png
    - assets/images/img.png
    - assets/images/turki_car.png
    - assets/images/turki.png
    - assets/images/medal.png
    - assets/images/w.png
    - assets/images/turki_icon.png
    - assets/images/money.png
    - assets/images/turki2.png
    - assets/images/t1.gif
    - assets/images/hary.png
    - assets/images/not_supported.png
    - assets/images/success.gif
    - assets/images/empty_cart.png
    - assets/language/ar.json
    - assets/language/en.json

  fonts:
    - family: Turki
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/light.otf
          weight: 300
    - family: RA7ICONS
      fonts:
        - asset: assets/icons/RA7ICONS.ttf
    - family: TURKIICONS
      fonts:
        - asset: assets/icons/TURKIICONS.ttf
    - family: RA1ICONS
      fonts:
        - asset: assets/icons/RA1ICONS.ttf
    - family: SOCIALICONS
      fonts:
        - asset: assets/icons/SocialIcons.ttf