name: turki_maraa_app
description: "Turki Dabayh app created by Rami Alamir"

publish_to: 'none'

version: 6.10.0+43

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  in_app_review: ^2.0.9
  http: ^1.2.2
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_analytics: ^11.2.1
  firebase_in_app_messaging: ^0.8.0+4
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.1
  provider: ^6.1.2
  auto_size_text: ^3.0.0
  webview_flutter: ^4.8.0
  flutter_advanced_drawer: ^1.3.6
  avatar_glow: ^3.0.1
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  flutter_spinkit: ^5.2.1
  pin_code_fields: ^8.0.1
#  flutter_picker: ^2.1.0
  readmore: ^3.0.0
  intl: ^0.19.0
  version: ^2.0.0
  tamara_flutter_sdk: ^1.0.10
  huawei_hmsavailability: ^6.12.0+300
  huawei_map: ^6.11.2+303
  huawei_location: ^6.12.0+302
  flutter_svg: ^2.0.10+1
  app_settings: ^5.1.1
  tabby_flutter_inapp_sdk: ^1.5.0
  get_it: ^7.7.0
  connectivity_plus: ^5.0.2
  lottie: ^3.1.2
  shake: ^2.2.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3
  rate_my_app: ^2.2.0
  localstorage: ^4.0.1+4
#flutter_native_splash:
#  background_image: "assets/images/ww1.png"
dev_dependencies:
#  flutter_native_splash:

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/profile_icons/
    - assets/language/
    - assets/lottie/
    - assets/images/ww1.png

  fonts:
    - family: Turki
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/light.otf
          weight: 300
    - family: Turki
      fonts:
        - asset: assets/fonts/harir/harir.otf
        - asset: assets/fonts/harir/harir_bold.otf
          weight: 700
    - family: TURKIICONS
      fonts:
        - asset: assets/icons/TURKIICONS.ttf
    - family: SOCIALICONS
      fonts:
        - asset: assets/icons/SocialIcons.ttf