// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AAAAg5KibHs:APA91bH3MCxkfFwNzvk46bk4hPPmsQcnRas2549F9K7IxWARe9IC-liRLsTG4PRVprp1MqGdX89YI1YU6KJDXkELxHQH2zq6vJWiUjKm1TmXa1ZTC0o8qnYBkkvLUv2SigpitRsO2eL9',
    appId: '1:565100833915:android:33474c957dbfda293d06de',
    messagingSenderId: '565100833915',
    projectId: 'turkieshop-c8917',
    storageBucket: 'turkieshop-c8917.firebasestorage.app',
    // androidClientId:
    //     '565100833915-2ll3glmk9t8fegl59vbeao5kq6sqihvm.apps.googleusercontent.com', // OAuth Client ID
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AAAAg5KibHs:APA91bH3MCxkfFwNzvk46bk4hPPmsQcnRas2549F9K7IxWARe9IC-liRLsTG4PRVprp1MqGdX89YI1YU6KJDXkELxHQH2zq6vJWiUjKm1TmXa1ZTC0o8qnYBkkvLUv2SigpitRsO2eL9',
    appId: '1:565100833915:android:33474c957dbfda293d06de',
    messagingSenderId: '565100833915',
    projectId: 'turkieshop-c8917',
    storageBucket: 'turkieshop-c8917.firebasestorage.app',
    androidClientId:
        '565100833915-2ll3glmk9t8fegl59vbeao5kq6sqihvm.apps.googleusercontent.com', // OAuth Client ID
    iosClientId:
        '565100833915-t8g9ndr0itcmp3cdgkc77b2pv7t6ff0q.apps.googleusercontent.com',
    iosBundleId: 'com.digishapes.turkieshop',
  );
}
