/// Flutter icons RA1ICONS
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RA1ICONS
///      fonts:
///       - asset: fonts/RA1ICONS.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RA1ICONS {
  RA1ICONS._();

  static const _kFontFam = 'RA1ICONS';
  static const String? _kFontPkg = null;

  static const IconData badge = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money__2_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money__1_ = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pay = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
