/// Flutter icons SocialIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialIcons
///      fonts:
///       - asset: fonts/SocialIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class SocialIcons {
  SocialIcons._();

  static const _kFontFam = 'SocialIcons';

  static const IconData account_circle = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
  static const IconData snapchat_5 = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
  static const IconData snapchat = IconData(
    0xe803,
    fontFamily: _kFontFam,
  );
  static const IconData facebook_2 = IconData(
    0xe805,
    fontFamily: _kFontFam,
  );
  static const IconData twitter = IconData(
    0xe806,
    fontFamily: _kFontFam,
  );
  static const IconData twitter_2 = IconData(
    0xe807,
    fontFamily: _kFontFam,
  );
  static const IconData facebook = IconData(
    0xe808,
    fontFamily: _kFontFam,
  );
  static const IconData instagram = IconData(
    0xe809,
    fontFamily: _kFontFam,
  );
  static const IconData instagram_2 = IconData(
    0xe80a,
    fontFamily: _kFontFam,
  );
}
