/// Flutter icons TURKIICONS
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TURKIICONS
///      fonts:
///       - asset: fonts/TURKIICONS.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TURKIICONS {
  TURKIICONS._();

  static const _kFontFam = 'TURKIICONS';
  static const String? _kFontPkg = null;

  static const IconData ask = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back_black = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calories = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_cash_colored = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_cash_uncolored = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_delete = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_favourite_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_location = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_minus = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_online_colored = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_online_uncolored = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_plus = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_cart = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_fill = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decrement = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_unfilled = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_delivery = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_location_white = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_merchant = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_search = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_sidemenu = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData increment = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_done_1 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product_cart = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabnav_cart = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabnav_help = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabnav_home = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabnav_myorders = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabnav_user = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_discount = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_1 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_delivered = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_delivering = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_done = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_preparing = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_quality = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_calling = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_favourite = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyrights = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData darkmode = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circle = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insta_colored = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insta_outline = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightmode = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout__1__1 = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_profile = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share4_1 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snap_colored = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_colored = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snap_outline = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_outline = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user6 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_money = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_wallet = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pay_money = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData points = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData present_card_1 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData present_card_2 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData present_card = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redeem_points = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_1 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
